export const popupProfile = document.querySelector('.popup-profile');//находим попап профиля
export const popupAvatar = document.querySelector('.popup-avatar');//находим попап аватара
export const popupPlace = document.querySelector('.popup-place');//находим попап места
export const popupImg = document.querySelector('.popup-img');//находим попап картинки
export const profile = document.querySelector('.profile');//находим профиль
export const editButton = profile.querySelector('.profile__edit-button');//находим кнопку редактирования профиля
export const closeProfileButton = popupProfile.querySelector('.popup__close-button'); //находим кнопку закрытия попапа профиля
export const saveButton = popupProfile.querySelector('.popup__button');//находим кнопку сохранения данных профиля
export const profileTitle = profile.querySelector('.profile__title');//находим заголовок профиля
export const profileSubtitle = profile.querySelector('.profile__subtitle');//находим подзаголовок профиля
export const profileAvatar = profile.querySelector('.profile__avatar-overlay');//находим оверлей аватара
export const profileAvatarImg = profile.querySelector('.profile__avatar');//находим картинку аватара
export const profileForm = popupProfile.querySelector('.popup__container');//находим форму профиля
export const nameInput = document.getElementById('name-input');//находим поле ввода имени
export const jobInput = document.getElementById('prof-input');//находим поле ввода профессии
export const avatarInput = document.getElementById('avatar-input');//находим поле ввода аватара
export const addButton = profile.querySelector('.profile__add-button');//находим кнопку открытия попапа место
export const closeButtonPlace = popupPlace.querySelector('.popup__close-button');//находим кнопку закрытия попапа место
export const closeButtonAvatar = popupAvatar.querySelector('.popup__close-button');//находим кнопку закрытия попапа аватар
export const elements = document.querySelector('.elements');//находим контейнер для карточек
export const imgPopupImg = popupImg.querySelector('.popup-img__image');//находим картинку попапа картинки
export const titlePopupImg = popupImg.querySelector('.popup-img__title');//находим название картинки попапа картинки
export const addPlaceForm = popupPlace.querySelector('.popup__container');//находим форму места
export const addAvatarForm = popupAvatar.querySelector('.popup__container');//находим форму аватара
export const saveButtonPlace = popupPlace.querySelector('.popup__button');//находим кнопку сохранить места
export const saveButtonAvatar = popupAvatar.querySelector('.popup__button');//находим кнопку сохранить аватара
export const placeInput = document.getElementById('place-input');//находим поле ввода названия места
export const linkInput = document.getElementById('email-input');// находим поле ввода ссылки
export const closeButtonImg = popupImg.querySelector('.popup__close-button');//находим кнопку закрытия попапа картинки
export const closeButtonBasket = document.querySelector('.elements__close-button');//находим кнопку корзинка